# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'AnimeTracker_MainWindow.ui'
#
# Created: Sun Dec 18 11:47:06 2011
#      by: PyQt4 UI code generator 4.8.6
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui
import NetworkHandler
import sys
try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    _fromUtf8 = lambda s: s

class Ui_MainWindow(object):
    #def __init__(self):
        #app = QtGui.QApplication(sys.argv)
        #MainWindow = QtGui.QMainWindow()
        #self.ui = Ui_MainWindow()
        #self.ui.setupUi(self)
        #MainWindow.show()
        #sys.exit(app.exec_())
    def setupUi(self, MainWindow):
        MainWindow.setObjectName(_fromUtf8("MainWindow"))
        MainWindow.resize(582, 385)
        MainWindow.setWindowTitle(QtGui.QApplication.translate("MainWindow", "MainWindow", None, QtGui.QApplication.UnicodeUTF8))
        self.centralwidget = QtGui.QWidget(MainWindow)
        self.centralwidget.setObjectName(_fromUtf8("centralwidget"))
        self.gridLayout_8 = QtGui.QGridLayout(self.centralwidget)
        self.gridLayout_8.setObjectName(_fromUtf8("gridLayout_8"))
        self.gridLayout_7 = QtGui.QGridLayout()
        self.gridLayout_7.setObjectName(_fromUtf8("gridLayout_7"))
        self.splitter_2 = QtGui.QSplitter(self.centralwidget)
        self.splitter_2.setOrientation(QtCore.Qt.Horizontal)
        self.splitter_2.setObjectName(_fromUtf8("splitter_2"))
        self.graphicsView = QtGui.QGraphicsView(self.splitter_2)
        self.graphicsView.setMaximumSize(QtCore.QSize(225, 350))
        self.graphicsView.setObjectName(_fromUtf8("graphicsView"))
        self.layoutWidget = QtGui.QWidget(self.splitter_2)
        self.layoutWidget.setObjectName(_fromUtf8("layoutWidget"))
        self.verticalLayout = QtGui.QVBoxLayout(self.layoutWidget)
        self.verticalLayout.setSizeConstraint(QtGui.QLayout.SetDefaultConstraint)
        self.verticalLayout.setMargin(0)
        self.verticalLayout.setObjectName(_fromUtf8("verticalLayout"))
        self.splitter = QtGui.QSplitter(self.layoutWidget)
        self.splitter.setOrientation(QtCore.Qt.Vertical)
        self.splitter.setObjectName(_fromUtf8("splitter"))
        self.label = QtGui.QLabel(self.splitter)
        self.label.setText(QtGui.QApplication.translate("MainWindow", "Synopsis", None, QtGui.QApplication.UnicodeUTF8))
        self.label.setObjectName(_fromUtf8("label"))
        self.synopsis_text_browser = QtGui.QTextBrowser(self.splitter)
        self.synopsis_text_browser.setObjectName(_fromUtf8("synopsis_text_browser"))
        self.editing_tree_widget = QtGui.QTreeWidget(self.splitter)
        self.editing_tree_widget.setObjectName(_fromUtf8("editing_tree_widget"))
        self.editing_tree_widget.headerItem().setText(0, _fromUtf8("1"))
        self.verticalLayout.addWidget(self.splitter)
        self.gridLayout_7.addWidget(self.splitter_2, 0, 0, 1, 1)
        self.verticalLayout_2 = QtGui.QVBoxLayout()
        self.verticalLayout_2.setObjectName(_fromUtf8("verticalLayout_2"))
        self.tabWidget = QtGui.QTabWidget(self.centralwidget)
        self.tabWidget.setObjectName(_fromUtf8("tabWidget"))
        self.tab = QtGui.QWidget()
        self.tab.setObjectName(_fromUtf8("tab"))
        self.gridLayout = QtGui.QGridLayout(self.tab)
        self.gridLayout.setObjectName(_fromUtf8("gridLayout"))
        self.watching_tree_widget = QtGui.QTreeWidget(self.tab)
        self.watching_tree_widget.setObjectName(_fromUtf8("watching_tree_widget"))
        self.watching_tree_widget.headerItem().setText(0, _fromUtf8("1"))
        self.gridLayout.addWidget(self.watching_tree_widget, 0, 0, 1, 1)
        self.tabWidget.addTab(self.tab, _fromUtf8(""))
        self.tab_3 = QtGui.QWidget()
        self.tab_3.setObjectName(_fromUtf8("tab_3"))
        self.gridLayout_2 = QtGui.QGridLayout(self.tab_3)
        self.gridLayout_2.setObjectName(_fromUtf8("gridLayout_2"))
        self.completed_tree_widget = QtGui.QTreeWidget(self.tab_3)
        self.completed_tree_widget.setObjectName(_fromUtf8("completed_tree_widget"))
        self.completed_tree_widget.headerItem().setText(0, _fromUtf8("1"))
        self.gridLayout_2.addWidget(self.completed_tree_widget, 0, 0, 1, 1)
        self.tabWidget.addTab(self.tab_3, _fromUtf8(""))
        self.tab_4 = QtGui.QWidget()
        self.tab_4.setObjectName(_fromUtf8("tab_4"))
        self.gridLayout_3 = QtGui.QGridLayout(self.tab_4)
        self.gridLayout_3.setObjectName(_fromUtf8("gridLayout_3"))
        self.plan_to_watch_tree_widget = QtGui.QTreeWidget(self.tab_4)
        self.plan_to_watch_tree_widget.setObjectName(_fromUtf8("plan_to_watch_tree_widget"))
        self.plan_to_watch_tree_widget.headerItem().setText(0, _fromUtf8("1"))
        self.gridLayout_3.addWidget(self.plan_to_watch_tree_widget, 0, 0, 1, 1)
        self.tabWidget.addTab(self.tab_4, _fromUtf8(""))
        self.tab_5 = QtGui.QWidget()
        self.tab_5.setObjectName(_fromUtf8("tab_5"))
        self.gridLayout_4 = QtGui.QGridLayout(self.tab_5)
        self.gridLayout_4.setObjectName(_fromUtf8("gridLayout_4"))
        self.dropped_tree_widget = QtGui.QTreeWidget(self.tab_5)
        self.dropped_tree_widget.setObjectName(_fromUtf8("dropped_tree_widget"))
        self.dropped_tree_widget.headerItem().setText(0, _fromUtf8("1"))
        self.gridLayout_4.addWidget(self.dropped_tree_widget, 0, 0, 1, 1)
        self.tabWidget.addTab(self.tab_5, _fromUtf8(""))
        self.tab_6 = QtGui.QWidget()
        self.tab_6.setObjectName(_fromUtf8("tab_6"))
        self.gridLayout_5 = QtGui.QGridLayout(self.tab_6)
        self.gridLayout_5.setObjectName(_fromUtf8("gridLayout_5"))
        self.on_hold_tree_widget = QtGui.QTreeWidget(self.tab_6)
        self.on_hold_tree_widget.setObjectName(_fromUtf8("on_hold_tree_widget"))
        self.on_hold_tree_widget.headerItem().setText(0, _fromUtf8("1"))
        self.gridLayout_5.addWidget(self.on_hold_tree_widget, 0, 0, 1, 1)
        self.tabWidget.addTab(self.tab_6, _fromUtf8(""))
        self.tab_2 = QtGui.QWidget()
        self.tab_2.setObjectName(_fromUtf8("tab_2"))
        self.gridLayout_6 = QtGui.QGridLayout(self.tab_2)
        self.gridLayout_6.setObjectName(_fromUtf8("gridLayout_6"))
        self.unset_tree_widget = QtGui.QTreeWidget(self.tab_2)
        self.unset_tree_widget.setObjectName(_fromUtf8("unset_tree_widget"))
        self.unset_tree_widget.headerItem().setText(0, _fromUtf8("1"))
        self.gridLayout_6.addWidget(self.unset_tree_widget, 0, 0, 1, 1)
        self.tabWidget.addTab(self.tab_2, _fromUtf8(""))
        self.verticalLayout_2.addWidget(self.tabWidget)
        self.progressBar = QtGui.QProgressBar(self.centralwidget)
        self.progressBar.setProperty("value", 24)
        self.progressBar.setObjectName(_fromUtf8("progressBar"))
        self.verticalLayout_2.addWidget(self.progressBar)
        self.gridLayout_7.addLayout(self.verticalLayout_2, 1, 0, 1, 1)
        self.gridLayout_8.addLayout(self.gridLayout_7, 0, 0, 1, 1)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtGui.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 582, 21))
        self.menubar.setObjectName(_fromUtf8("menubar"))
        self.menuFile = QtGui.QMenu(self.menubar)
        self.menuFile.setTitle(QtGui.QApplication.translate("MainWindow", "File", None, QtGui.QApplication.UnicodeUTF8))
        self.menuFile.setObjectName(_fromUtf8("menuFile"))
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtGui.QStatusBar(MainWindow)
        self.statusbar.setObjectName(_fromUtf8("statusbar"))
        MainWindow.setStatusBar(self.statusbar)
        self.actionRescan_Directories = QtGui.QAction(MainWindow)
        self.actionRescan_Directories.setText(QtGui.QApplication.translate("MainWindow", "Rescan Directories", None, QtGui.QApplication.UnicodeUTF8))
        self.actionRescan_Directories.setObjectName(_fromUtf8("actionRescan_Directories"))
        self.actionSettings = QtGui.QAction(MainWindow)
        self.actionSettings.setText(QtGui.QApplication.translate("MainWindow", "Settings", None, QtGui.QApplication.UnicodeUTF8))
        self.actionSettings.setObjectName(_fromUtf8("actionSettings"))
        self.actionRefresh_List = QtGui.QAction(MainWindow)
        self.actionRefresh_List.setText(QtGui.QApplication.translate("MainWindow", "Refresh List", None, QtGui.QApplication.UnicodeUTF8))
        self.actionRefresh_List.setObjectName(_fromUtf8("actionRefresh_List"))
        self.actionUpdate_MAL = QtGui.QAction(MainWindow)
        self.actionUpdate_MAL.setText(QtGui.QApplication.translate("MainWindow", "Update MAL", None, QtGui.QApplication.UnicodeUTF8))
        self.actionUpdate_MAL.setObjectName(_fromUtf8("actionUpdate_MAL"))
        self.menuFile.addAction(self.actionRefresh_List)
        self.menuFile.addAction(self.actionUpdate_MAL)
        self.menuFile.addSeparator()
        self.menuFile.addAction(self.actionRescan_Directories)
        self.menuFile.addAction(self.actionSettings)
        self.menubar.addAction(self.menuFile.menuAction())

        self.retranslateUi(MainWindow)
        self.tabWidget.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

        #self.actionRefresh_List.connect(self.refresh_anime_list())

    def retranslateUi(self, MainWindow):
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab), QtGui.QApplication.translate("MainWindow", "Watching", None, QtGui.QApplication.UnicodeUTF8))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_3), QtGui.QApplication.translate("MainWindow", "Completed", None, QtGui.QApplication.UnicodeUTF8))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_4), QtGui.QApplication.translate("MainWindow", "Plan To Watch", None, QtGui.QApplication.UnicodeUTF8))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_5), QtGui.QApplication.translate("MainWindow", "Dropped", None, QtGui.QApplication.UnicodeUTF8))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_6), QtGui.QApplication.translate("MainWindow", "On Hold", None, QtGui.QApplication.UnicodeUTF8))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_2), QtGui.QApplication.translate("MainWindow", "Unset", None, QtGui.QApplication.UnicodeUTF8))

    def refresh_anime_list(self):
        network_object = NetworkHandler.NetworkHandler()
        network_object.start()


